Fix urlretrieve import for Python 3 (#3)
* Fix urlretrieve import for Python 3

Fix `AttributeError: 'module' object has no attribute 'urlretrieve'` on Python 3, by importing urllib.request
(ref: https://stackoverflow.com/questions/17960942/attributeerror-module-object-has-no-attribute-urlretrieve)

* Remove unused import